version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    build: ./excursion-backend
    # depends_on:
    #   - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/app_db
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"
    # restart: always

  frontend:
    build: ./excursion-frontend
    ports:
      - "5173:5173"
    restart: always
    # depends_on:
      # - backend
    volumes:
      - ./excursion-frontend:/app
      - /app/node_modules

    working_dir: /app
    command: npm run host

volumes:
  db_data:
